FEATURE: Automate release of surround lib from Codefresh
a2i2/surround pull request #255
Opened 2020-12-03 06:43 UTC by AkshatBajaj

2020-12-03 22:43 UTC, ucokzeko commented
As discussed on the call:
1. Look into automatically pushing tags to repo before releasing to `Pypi`
2. Look into linking test Codefresh pipeline into the release pipeline

2020-12-04 06:02 UTC, AkshatBajaj commented
/test

2020-12-04 06:03 UTC, AkshatBajaj commented
/test

2020-12-04 06:11 UTC, AkshatBajaj commented
/test

2020-12-04 06:46 UTC, AkshatBajaj commented
> As discussed on the call:
> 
> 1. Look into automatically pushing tags to repo before releasing to `Pypi`
> 2. Look into linking test Codefresh pipeline into the release pipeline

I used a different approach now, it is again based on the tags, please have a look

2020-12-04 06:51 UTC, AkshatBajaj commented
/test

2020-12-07 06:12 UTC, ucokzeko requested changes
Please do the same for `test` stage as well

What's the reason we are going back to version tagging for a release?

2020-12-07 06:12 UTC, ucokzeko commented on codefresh.yml
> +    type: parallel
Add `stage: "release"` above this

2020-12-07 06:12 UTC, ucokzeko commented on codefresh.yml
> +        stage: "release"
This can be removed

2020-12-07 06:12 UTC, ucokzeko commented on codefresh.yml
> +        stage: "release"
This too

2020-12-07 21:40 UTC, AkshatBajaj commented
> Please do the same for `test` stage as well
> 
> What's the reason we are going back to version tagging for a release?

It is based on Rohan's suggestion, he recommended we are better off with the tags and it is possible with the Codefresh for monorepos, we anyway solved the problem we were facing, so seems like a good approach to me :)

2020-12-07 22:16 UTC, ucokzeko commented
> It is based on Rohan's suggestion, he recommended we are better off with the tags and it is possible with the Codefresh for monorepos, we anyway solved the problem we were facing, so seems like a good approach to me :)

Yeah, it's all good :+1:
Just checking the reasoning behind this decision.

2020-12-07 22:16 UTC, ucokzeko approved these changes

2020-12-07 22:16 UTC, merged