[WIP] FEATURE: Integrate Hydra with Surround
a2i2/surround pull request #276
Opened 2021-01-13 04:27 UTC by zacbrannelly

## Summary of changes
* Created a `@dataclass` called `SurroundConfig`. This will contain the Surround specific configuration that determines how Surround will behave when running the pipeline. This contains the following properties:
    * `surface_exceptions` - Boolean value that determines if any exception thrown by the pipeline is allowed to reach the surface, or be squashed by Surround. 
    * `enable_stage_output_dump` - Boolean value that determines if the `dump_output` method of each `Stage` in the pipeline is called after execution.
* Created a `@dataclass` called `BaseConfig`. This will contain all the base information that a typical Surround project will require. This mainly includes automatically generated paths that can then be used in the pipeline to do things like load data (`input_path`), load models (`model_path`) and save output (`output_path`). These fields were present in the original config implementation. This also includes a field for the `SurroundConfig` class described above. This class is intended to be extended in a Surround project, to allow the adding of custom fields.

Example usage:
```python
from surround import Assembler, BaseConfig
from surround.surround_config import has_config
from .stages import InputValidator, Baseline

class Config(BaseConfig):
    some_property: str = "Default value"
   
@has_config(name="config", config_class=Config)
def main(config: Config) -> None:
    Assembler("baseline", config)
        .set_stages([InputValidator(), Baseline()])
    ...
```

This also works with the standard Hydra way of doing things which comes with built-in command line functionality (can override config by specifying arguments e.g. `python3 -m module some_property=test`:
```python
import hydra
from hydra.core.config_store import ConfigStore

from surround import Assembler, BaseConfig
from .stages import InputValidator, Baseline

class Config(BaseConfig):
    some_property: str = "Default value"
   
cs = ConfigStore.instance()
cs.store(name='config', node=Config)

@hydra.main(config_name="config")
def main(config: Config) -> None:
    Assembler("baseline", config)
        .set_stages([InputValidator(), Baseline()])
    ...
```

Then to override config you can provide a `config.yaml` e.g:
```yaml
some_property: Override!
```

## Limitations
You can no longer load config automatically like in the previous implementation with `Config(auto_load=True)`, Hydra needs to be aware of the config class and the name of the config (e.g. when the name is `config` it will look for `config.yaml` for overrides) to be able to load it automatically.

## TODO
- [ ] Use Hydra in the generated project.
- [ ] Confirm generated project still functions as expected.
- [ ] Find out if the `surround_cli` tool `config` is needed anymore (was used to set name and email, plus some experiment config).
- [ ] If this tool is needed then try integrate Hydra into it.
- [ ] Rip out usages of old implementation `Config` and delete the class.

2021-02-12 05:17 UTC, zacbrannelly commented
@ScottyB This is good for a review

2021-02-12 09:09 UTC, omry commented
Hi, looks pretty good.
One comment about load_config:
it looks like you are trying to determine the config searchpath and then use the compose API.

Take a look at the ConfigSearchPathPlugin, it lets you add the framework to the searchpath automatically.
[Here](https://github.com/facebookresearch/hydra/tree/1.0_branch/examples/plugins/example_searchpath_plugin) is a working example.

Also read [this](https://hydra.cc/docs/advanced/plugins) to learn more about plugins.

2021-04-19 03:48 UTC, AkshatBajaj requested changes
Conceptually it seems good, but I am not able to run the PR with the advertised changes

<img width="1080" alt="Screen Shot 2021-04-19 at 1 44 24 pm" src="https://user-images.githubusercontent.com/32318980/115178805-653fd780-a115-11eb-9d69-ff9e95500763.png">

When I do import the config using: `from .config import Config`
I get the following error:
<img width="1073" alt="Screen Shot 2021-04-19 at 1 45 43 pm" src="https://user-images.githubusercontent.com/32318980/115178905-8dc7d180-a115-11eb-9869-15deaf7ecdfe.png">

I am not sure if I am missing anything but if I am, probably worth adding that to the docs

2021-08-29 23:42 UTC, zacbrannelly commented on examples/hydra_example/notebooks/data_analysis.ipynb
> +    "os.chdir('/app')"
I think this notebook is assuming it is being ran in a container. Since we put the app code in `/app` in the `Dockerfile`.

2021-08-29 23:42 UTC, zacbrannelly commented on examples/testing/testing/config.yaml
> +image: testing
Looks like an accidental commit 😅

2021-08-29 23:45 UTC, zacbrannelly commented
/test

2021-08-29 23:48 UTC, ucokzeko commented
/test

2021-08-30 02:25 UTC, ucokzeko reviewed
Otherwise, works nicely

2021-08-30 02:25 UTC, ucokzeko commented on surround_cli/templates/new/init.py.txt
>  import logging
Can be removed, not used

2021-08-30 02:25 UTC, ucokzeko commented on surround/surround/config.py
> +    output_path: Optional[str] = field(default_factory=lambda: os.path.join(get_project_root_or_cwd(), "output", str(datetime.now().strftime("%Y-%m-%d-%H-%M-%S"))))
There are 2 different output directory now, one here (`output/datetime format`) and the other one is from Hydra (`outputs/date/time`). Is this expected?

<img width="276" alt="Screen Shot 2021-08-30 at 12 18 51 pm" src="https://user-images.githubusercontent.com/5424737/131276236-0d9f95aa-43a3-4281-8069-61559ac0767d.png">

2021-08-30 03:48 UTC, ucokzeko commented
/test

2021-08-30 03:55 UTC, ucokzeko commented
/test

2021-08-30 04:02 UTC, ucokzeko approved these changes
LGTM
Getting this in for now

2021-08-30 04:02 UTC, merged